-- 19 학번만 조회
SELECT STUDENT_ID AS 학번, NAME AS 이름, MAJOR AS 전공
FROM USERS
WHERE REGEXP_LIKE(STUDENT_ID, '2019[0123456789]');

-- 17 학번만 조회
SELECT STUDENT_ID AS 학번, NAME AS 이름, MAJOR AS 전공
FROM USERS
WHERE REGEXP_LIKE(STUDENT_ID, '2017[0123456789]');

-- 화학과
SELECT STUDENT_ID AS 학번, NAME AS 이름
FROM USERS
WHERE MAJOR = '화학과';

-- 18 학번, 컴퓨터공학부 조회
SELECT STUDENT_ID AS 학번, NAME AS 이름
FROM USERS
WHERE REGEXP_LIKE(STUDENT_ID, '2018[0123456789]') AND MAJOR = '컴퓨터공학부';

-- 수요일에 진행하는 활동그룹
SELECT NAME AS 활동명, PERIOD AS 기한, PLACE AS 장소, STUDENT_ID AS 팀장
FROM GROUPS
WHERE DAY_CYCLE = '수';

-- 회비를 사용한 그룹 그리고 사용한 횟수
SELECT g.NAME as 활동명, count(*) as 사용횟수
FROM GROUPS g, MEMBERSHIP m
WHERE g.NO = m.GROUPS_NO
GROUP BY g.NAME;

-- 회비를 사용한 그룹 중 3만원 이상
SELECT g.NAME as 활동명
FROM GROUPS g, MEMBERSHIP m
WHERE g.NO = m.GROUPS_NO AND m.PRICE >= 40000;

-- 대출된 도서
SELECT NAME AS 책이름, AUTHOR AS 저자, PUBLISHER AS 출판사, STUDENT_ID AS 대여자_학번
FROM BOOKS
WHERE STUDENT_ID IS NOT NULL;

-- 대출되지 않은 도서
SELECT NAME AS 책이름, AUTHOR AS 저자, PUBLISHER AS 출판사
FROM BOOKS
WHERE STUDENT_ID IS NULL;

-- 대출 반납기한이 지난 도서
SELECT NAME AS 책이름, RETURN_DATE AS 반납일, STUDENT_ID AS 대여자_학번
FROM BOOKS
WHERE RETURN_DATE < (
    SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
    FROM DUAL
);
